In [33]:
from FileOpener.CSVReader.CSVReader import CSVReader as csv
import FileOpener.new_backtest as newb

In [2]:
fn_directory = "CSVFile/FinancialData/Korea"
fn_kdq_opq = "OP_INCOME_KDQ.csv" 
fn_kse_opq = "OP_INCOME_KSE.csv" 

kdq_opq = csv.financial_reader(directory=fn_directory, filename=fn_kdq_opq)
kse_opq = csv.financial_reader(directory=fn_directory, filename=fn_kse_opq)

## 분기별 적전
    ## 분기별 연간 누적 영업이익
    ## 전분기 흑자 / 현분기 적자: 적전

In [16]:
def ptod_screen(fn_opq):
    
    current = fn_opq.shift(1).rolling(window=4).sum() 
    bef = current.shift(1)
    
    return (current < 0) & (bef > 0)

In [17]:
kdq_opq_scr = ptod_screen(kdq_opq)
kse_opq_scr = ptod_screen(kse_opq)

In [18]:
kdq_opq_scr.tail()

,A000250,A000440,A001000,A001540,A001810,A001840,A002230,A002290,A002680,A002800,...,A900280,A900290,A900300,A900310,A900340,A950110,A950130,A950140,A950160,A950170
Code,,,,,,,,,,,,,,,,,,,,,
2017-09-30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2017-12-31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2018-03-31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2018-06-30,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2018-09-30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
kse_opq_scr.tail()

,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000100,A000120,A000140,...,A293480,A294870,A298000,A298020,A298040,A298050,A298690,A300720,A306200,A900140
Code,,,,,,,,,,,,,,,,,,,,,
2017-09-30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2017-12-31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2018-03-31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2018-06-30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2018-09-30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [22]:
prc_directory = "CSVFile/Price/Korea/Stocks/"
fn_kdq_cls = "KOSDAQ_FROM_1998_close.csv"
fn_kse_cls = "KOSPI_FROM_1998_close.csv"

kdq_prc = csv.price_reader(directory=prc_directory, filename=fn_kdq_cls)
kse_prc = csv.price_reader(directory=prc_directory, filename=fn_kse_cls)

In [23]:
kdq_back_obj = newb.Financial(price=kdq_prc)
kse_back_obj = newb.Financial(price=kdq_prc)

In [25]:
kdq_rt = kdq_back_obj.backtest(kdq_opq_scr, 'Q')
kse_rt = kdq_back_obj.backtest(kdq_opq_scr, 'Q')

D:\Udemy_Course\TradingDev\WiseData\FileOpener\new_backtest.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  ret.loc[:'1998-05-23'][ret.loc[:'1998-05-23'] > 1.08] = 1.08
C:\Users\DELL\Anaconda3\lib\site-packages\pandas\core\frame.py:3160: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._where(-key, value, inplace=True)
D:\Udemy_Course\TradingDev\WiseData\FileOpener\new_backtest.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  ret.loc['1998-05-25':'2005-03-25'][ret.loc['1998-05-25':'2005-03-25'] > 1.12] = 1.12
D:\Udemy_Course\TradingDev\WiseData\FileOpener\new_backtest.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  ret.loc['2005-03-28':'2015-06-14'][ret.loc['2005-03-28':'2015-06-14'] > 1.15] = 1.15
D:\Udemy_Course\TradingDev\WiseData\FileOpener\new_backtest.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  ret.loc['2015-06-15':][ret.loc['2015-06-15':] > 1.3] = 1.3

In [34]:
test = newb.PFAnalysis.PfOneWay(kdq_rt)

In [35]:
test.preety_print('Q')

AttributeError: 'PfOneWay' object has no attribute 'cumReturn'